// Code generated by mockery v2.36.0. DO NOT EDIT.

package mockparser

import (
	http "net/http"

	metric "github.com/kuzhukin/metrics-collector/internal/metric"
	mock "github.com/stretchr/testify/mock"
)

// BatchRequestParser is an autogenerated mock type for the BatchRequestParser type
type BatchRequestParser struct {
	mock.Mock
}

// BatchParse provides a mock function with given fields: r
func (_m *BatchRequestParser) BatchParse(r *http.Request) ([]*metric.Metric, error) {
	ret := _m.Called(r)

	var r0 []*metric.Metric
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) ([]*metric.Metric, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) []*metric.Metric); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*metric.Metric)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBatchRequestParser creates a new instance of BatchRequestParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBatchRequestParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *BatchRequestParser {
	mock := &BatchRequestParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
